[versions]
# libraries
junit = "4.13.2"
jupiter = "5.13.4"

# plugins
changelog = "2.5.0"
kotlin = "2.2.21"
intelliJPlatform = "2.10.5"
qodana = "2025.2.4"

[libraries]
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }