[versions]
# libraries
junit = "4.13.2"
jupiter = "6.0.1"

# plugins
changelog = "2.5.0"
kotlin = "2.3.0"
intelliJPlatform = "2.11.0"
qodana = "2025.3.1"

[libraries]
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }